### ISSUE TITLE
Support calculating bucket_id based on ddl.sharding_key

### ISSUE THREAD

**Issue by sharonovd** [tarantool/crud#166]
Crud/ddl/migrations is a way to go for our customers. But project after a project I observe the following clutches:

```lua
local function get_object_by_pk(part1, part2)    
    local bucket_id = vshard.router.bucket_id_mpcrc32(part2)    
    local settings, err_settings = crud.get('object', {part1, part2}, {bucket_id = bucket_id})   
    if err_settings ~= nil then return nil, err_settings    end    
    return settings
end

local function upsert_object(object)    
    local id = settings["id"]    
    local bucket_id = vshard.router.bucket_id_mpcrc32(id)
    local res, err = crud.replace_object("settings_object", settings, {bucket_id = bucket_id})    
    if err ~= nil then        return nil, err    end    
end
```

But this info is already present in ddl! (`ddl.register_sharding_key('object', {"id"})`)
This shoould work out-of-the-box

**Comment by artur-barsegyan** [comment]
## TODO:
- [ ]  Поддержка `sharding_key` из CRUD (описано выше)
- [ ]  Поддержка кастомных шард функций в DDL 
- [ ]  DDL API
    - [ ]  `ddl.bucket_id()` 
    - [ ]  `ddl.*.set_sharding_opts`
    
Подробнее о каждом из пунктом описано [в Notion.](https://www.notion.so/tarantool/DDL-1811eb0c2efa4168b7aa79a93c519450)

**Comment by artur-barsegyan** [comment]
As part of the pull request https://github.com/tarantool/crud/pull/181, I saw that there was a commit with a change to the default hash function.

I wrote an issue with details about that problem: #185. We should implement it in the current scope of work. Without that we can't deliver:
- CRUD + DDL feature for our paid customers
- The new Getting started with CRUD on-board

**Comment by ligurio** [comment]
@Totktonada, generally, you are right. Additionally `select()` was required sharding key support too.

To sum up

| CRUD method      | Added sharding key support |
| ---------------- | ----------- |
| `get()`                       | Yes |
| `insert()` / `insert_object()` | Yes |
| `delete()`        | Yes |
| `replace()` / `replace_object()` | Yes |
| `upsert()` / `upsert_object()` | Yes |
| `select()` / `pairs()` | Yes |
| `update()`       | Yes |
| `upsert()` / `upsert_object()` | Yes |
| `replace()` / `replace_object()` | Yes | 
| `min()` / `max()` | **No** (not required) |
| `cut_rows()` / `cut_objects()`  | **No** (not required) |
| `truncate()`  | **No** (not required) |
| `len()` | **No** (not required) |

> So the task is about automatic calculation of bucket_id, when we have schema information (sharding keys, sharding functions) and all necessary data in an operation arguments, correct?

Automatic bucket_id calculation doesn't require any additional options or arguments, but the user should care about specifying the correct sharding key in DDL schema or space `_ddl_sharding_key`.

> It means the following possible sub-tasks:
>
> Autodetermine bucket_id (when sharding keys and sharding functions are known), when the sharding key parts are all parts of > the primary key (in any order, maybe with repeating), for {O} operations.
> Autodetermine bucket_id (when sharding keys and sharding functions are known) for insert/replace/upsert (and their _object > counterparts) ({O'}).

Seems we don't need any additional tickets.
